### ISSUE TITLE
Update Normative References

### ISSUE THREAD

**Issue by SteveLLamb** [SMPTE/st430-5#1]
Amend to fix references to 430-1, 430-2, 429-8.
-	Part of the 429-8 project

**Comment by msheby** [comment]
ST 429-3:2007 has been approved for maintenance, so that will be revised as well.

**Comment by msheby** [comment]
RFC 6931 obsoleted by RFC 9231.

**Comment by twechsel** [comment]
A redlined ST430-5 document has been uploaded to umbrella issue #6, which includes the changes for this issue.

**Comment by twechsel** [comment]
The redlined ST430-5 document including changes directed to this issue can be found here:
https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/ETBPfieAa_FKntkCRXEiMSkBRYDmK4yT-3I5k54xRe4tlg?e=NYgsKj

**Comment by palemieux** [comment]
@twechsel Did you check whether a log created per RFC 4514 was compatible with a log created per RFC 2253? More importantly, RFC 2253 is referenced through [XML-Signature Syntax and Processing]:

_The Distinguished Name value in all X509IssuerName elements shall be compliant with RFC 2253 per [XML-Signature Syntax and Processing]._

Two observations:

* XML-Signature Syntax and Processing is not a normative reference
* RFC 2253 is not referenced in [XML-Signature Syntax and Processing](https://www.w3.org/TR/xmldsig-core1/)

Any opinion? I recall your mentioning that you were co-editors of the spec.

**Comment by palemieux** [comment]
@twechsel RFC 3280 is not referenced in the prose. Is it (or RFC 5280) needed?

**Comment by twechsel** [comment]
I recommend deleting RFC 3280/5280.  I note it’s also referenced in ST430-4 (Log Record Format Specification), but does not appear in the prose there either.

Tony

**Comment by twechsel** [comment]
I did not check whether a log created under the more recent spec is compatible.  Matt Sheby was kind enough to provide most of the updated RFC numbers, and I checked them before just plugging them in.

 

I was co-editor of the standard, but my contributions were directed to what records were needed, and their contents/exceptions.  Bill Elswick was the power house behind all the XML and IETF stuff for both this and the sister spec ST430-4.  I don’t have an opinion about what you’ve uncovered, but I’m sure the group would like your recommendation(s).  (I did notice that RFC 4514/2253 apparently does not appear in the prose.)

Tony

**Comment by twechsel** [comment]
I asked Bill Elswick (who was the editor of ST430-5 and the umbrella st430-4 standard) about this.  Bill suggested we could reference RFC4514 directly (and drop the reference to XML-Signature Syntax and Processing), but only once a compatibility match is confirmed with current practice.  In other words, confirm that a log created per RFC 4514 is compatible with a log created per RFC 2253.

I found the earlier version of XML-Signature Syntax and Processing that was in effect when st430-5 was written: https://www.w3.org/TR/2002/REC-xmldsig-core-20020212/ .  At section 4.4.4 it references RFC2253.  The current XML-Sig. version (https://www.w3.org/TR/xmldsig-core1/#sec-X509Data ) references section 2 of RFC4514 in analogous section 4.5.4.1.  When I compared the material of RFC4514 section 2 to that of RFC2253 they appear to be the same, but I am not sufficiently qualified in this area to be sure. 

So I’m asking implementers to take a look and provide input.

**Comment by palemieux** [comment]
Addressed at https://github.com/SMPTE/st430-5-private/commit/84dfa0b0d5c3072fb8e06553c22e4c1a60517419.

Few observations:

* [XML digital signature](https://www.w3.org/TR/xmldsig-core1/) was in fact referenced through the `ds` namespace in Table 1

* [XML digital signature](https://www.w3.org/TR/xmldsig-core1/) references RFC 4514 in its _Distinguished Name Encoding Rules_ section.

So I think it is ok to drop the direct reference to RFC 4514 and instead reference the Distinguished Name Encoding Rules of [XML digital signature](https://www.w3.org/TR/xmldsig-core1/)

**Comment by twechsel** [comment]
Agreed.  And I think Matt Sheby was also going to take a look.
