### ISSUE TITLE
Clause 3: Confirming Latest Editions

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-5#157]
The last two Normative Reference items are as follows:
![image](https://github.com/SMPTE/st430-5/assets/118845840/5eb7c022-550f-452d-9814-a128b373722e)

The W3C XML Schema Part 1: Structures document is dated 2004.
The W3C XML Signature Syntax and Processing Version 1.1 document is dated 2013.

Confirming that these are indeed the latest editions.

**Comment by palemieux** [comment]
Confirmed
