### ISSUE TITLE
OBAE Forensic Marking

### ISSUE THREAD

**Issue by HaroldHallikainen** [SMPTE/st430-5#2]
From Anthony Wechselberger, on behalf of DCI:

I noted there was another change needed for st430-5 (unrelated to st430-17) for OBAE forensic marking, and I was asked to provide information accordingly.  Below is published DCI erratum #5 to DCSS v1.3:
"For the FrameSequencePlayed Record (SMPTE ST 430-5 section 7.3.1.1), if the track file is an OBAE track tile, the Parameters list shall contain a name/value pair whose name element shall contain the token OBAEMark, and whose Value element shall contain one of two tokens, either "true" or "false", indicating that a forensic mark was or was not inserted during playout."  

This language is modeled on st430-5 language for existing FM marking of main sound, and establishes a similar parameter for immersive audio (referred to as OBAE within the DCSS).

**Comment by twechsel** [comment]
A redlined ST430-5 document has been uploaded to umbrella issue #6, which includes the changes of this issue.

**Comment by twechsel** [comment]
The redlined ST430-5 document including changes directed to this issue can be found here:
https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/ETBPfieAa_FKntkCRXEiMSkBRYDmK4yT-3I5k54xRe4tlg?e=NYgsKj

**Comment by palemieux** [comment]
Addressed at https://github.com/SMPTE/st430-5-private/commit/84dfa0b0d5c3072fb8e06553c22e4c1a60517419. Please review.
