### ISSUE TITLE
Definition of Security Manager not compatible with DCI MMB architecture

### ISSUE THREAD

**Issue by ki-bo** [SMPTE/st430-5#3]
When drafting ST 430-17 (SMS-OMB communications protocol), it was found that the Security Manager definition in 430-5 is not compliant with the Multiple Media Block (MMB) architecture used as the basis for the mentioned protocol. Specifically, the following requirements in 430-5 about the Security Manager in section 5.1 are not compatible with an MMB environment:

1. "It is implemented within the Image Media Block."
Conflict: An Outboard Media Block (OMB) does contain an SM, as well.

2. "There is a single Security Manager associated with each auditorium within an exhibition site."
Conflict: Each media block does contain its own instance of an SM.

**Comment by twechsel** [comment]
A redlined ST430-5 document has been uploaded to umbrella issue #6, which includes the changes of this issue.

**Comment by twechsel** [comment]
The redlined ST430-5 document including changes directed to this issue can be found here:
https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/ETBPfieAa_FKntkCRXEiMSkBRYDmK4yT-3I5k54xRe4tlg?e=NYgsKj

**Comment by palemieux** [comment]
@twechsel Addressed at https://github.com/SMPTE/st430-5-private/commit/84dfa0b0d5c3072fb8e06553c22e4c1a60517419 . Please review.
