### ISSUE TITLE
6.3, Paragraph 1, Sentences 1-3: Document or Standard?; Add space after "defines"

### ISSUE THREAD

**Issue by ERyan71258** [SMPTE/st430-5#44]
The sentences state:
This document defines and constrains the Security Log Event Class. Log Records of this class shall conform to the specifications and constraints in this document. This document also definesEvent Types and Event SubTypes for the Security Event Class.

Would it be more accurate to state:
This standard defines and constrains the Security Log Event Class. Log Records of this class shall conform to the specifications and constraints of this standard. This standard also defines Event Types and Event SubTypes for the Security Event Class.

Also: In Sentence 3, add space after "defines": "...also defines Event Types and..."

**Comment by palemieux** [comment]
Assuming we follow the ISO guidelines, then "document" is correct.
