### ISSUE TITLE
Addition of three new FrameSequencePlayed exception tokens

### ISSUE THREAD

**Issue by twechsel** [SMPTE/st430-5#5]
DCI requests the addition of three new exception tokens to the FrameSequencePlayed Record, and that these be listed in the “Exception Tokens and Definitions” table at section 7.4:
- PlayoutInterrupt – Indicates a playout was paused or restarted.
-  IntegrityPackError – Indicates a playout was disallowed or terminated due to missing content integrity pack metadata.
- CPLProcessedCollectError – Indicates a playout was disallowed or terminated due to failure to meet playout log collection requirements.

**Comment by twechsel** [comment]
A redlined ST430-5 document has been uploaded to umbrella issue #6, which includes the changes of this issue.

**Comment by twechsel** [comment]
The redlined ST430-5 document including changes directed to this issue can be found here:
https://smpte.sharepoint.com/:w:/s/21DC-DocumentMaintenance/ETBPfieAa_FKntkCRXEiMSkBRYDmK4yT-3I5k54xRe4tlg?e=NYgsKj

**Comment by palemieux** [comment]
@twechsel  Addressed at [84dfa0b0d5c3072fb8e06553c22e4c1a60517419](https://github.com/SMPTE/st430-5-private/commit/84dfa0b0d5c3072fb8e06553c22e4c1a60517419). Please review.
