### ISSUE TITLE
Request the generation of a revised ST430-5 document

### ISSUE THREAD

**Issue by twechsel** [SMPTE/st430-5#6]
DCI requests that all existing ST430-5 Security Log Event standard Github issues, be incorporated into a revised ST 430-5 document

**Comment by twechsel** [comment]
At the 8-11-22 document maintenance meeting it was agreed that I'd produce a ST430-5 Word document redline reflecting "issue" changes.  Except for issue #4 (which is in Pierre's hands) I have done so.  I have only addressed the issues, and not attempted to review the entire document for compliance to current SMPTE document requirements or formats, or updated the table of contents. 

ST430-5-201X (revision redline) 8-12-22

**Comment by twechsel** [comment]
[ST430-5-201X_revision-redline_8-12-22.docx](https://github.com/SMPTE/st430-5/files/9377026/ST430-5-201X_revision-redline_8-12-22.docx)

**Comment by SteveLLamb** [comment]
@twechsel please post on SMPTE Teams/Sharepoint and only put link here. We're not to be putting docs here directly here just yet.

**Comment by palemieux** [comment]
Document provided
